# 公共配置文件
spring:
  application:
    name: yaziApi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: none # 没有本地缓存，所以设置为none
#     30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    url: jdbc:mysql://localhost:3306/yazi_Api?useSSl=false;sueUnicode=true;characterEncoding=UTF-8;serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #使用Druid的数据源；

  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000

# rabbitmq 的配置： 端口：5672  webUI :15672
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

  #  password: 123456
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8111
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

#设置鱼聪明的密钥：
yuapi:
  client:
    access-key: y8rwjvw40zypdwbza9xu6ipx0728vopi
    secret-key: 3cd0lnrlxa2gcp7iyv7n8hsbdx1bbmgy


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


#dubbo的配置
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1 # 表示随机分配端口
  registry:
    id: nacos-registry
    address: nacos://localhost:8848?username=nacos&password=nacos


# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

# 自定义的sdk
yaziapi:
  client:
    access-key: jiangyanming
    secret-key: 123456